<?php
 /**
  * THIS FILE IS GENERATED BY RAPTOR EXPORTER, TO EASLY UPLOAD THIS FILE AGAIN INTO THE 
  * DATABASE USE THE IMPORTER CLASS.
  * 
  * Generated January 17 2016 09:23:52 PM
  */
 
$create=array (
  0 => 'Raptor2\\SyntarsusBundle\\Model\\Entity\\SecurityCategory',
  1 => 'Raptor2\\SyntarsusBundle\\Model\\Entity\\SecurityEstructure',
  2 => 'Raptor2\\SyntarsusBundle\\Model\\Entity\\SecurityPrivilege',
  3 => 'Raptor2\\SyntarsusBundle\\Model\\Entity\\SecurityRol',
  4 => 'Raptor2\\SyntarsusBundle\\Model\\Entity\\SecurityTrace',
  5 => 'Raptor2\\SyntarsusBundle\\Model\\Entity\\SecurityUser',
);
$data=array (
  'security_category' => 
  array (
    0 => 
    array (
      'id' => '1',
      'name' => 'normal',
    ),
  ),
  'security_estructure' => 
  array (
    0 => 
    array (
      'id' => '1',
      'id_category' => NULL,
      'name' => 'Raptor2',
      'description' => 'Base',
      'belongs' => '0',
    ),
  ),
  'security_privilege' => 
  array (
    0 => 
    array (
      'id' => '6',
      'route' => NULL,
      'name' => 'Security',
      'class_name' => '',
      'type' => '2',
      'belongs' => '0',
    ),
    1 => 
    array (
      'id' => '8',
      'route' => '/syntarsus/user/listestructure',
      'name' => 'listestructure',
      'class_name' => NULL,
      'type' => '1',
      'belongs' => '7',
    ),
    2 => 
    array (
      'id' => '9',
      'route' => '/syntarsus/user',
      'name' => 'User Manager',
      'class_name' => NULL,
      'type' => '0',
      'belongs' => '6',
    ),
    3 => 
    array (
      'id' => '27',
      'route' => '/syntarsus/rol',
      'name' => 'Rol Manager',
      'class_name' => NULL,
      'type' => '0',
      'belongs' => '6',
    ),
    4 => 
    array (
      'id' => '34',
      'route' => '/syntarsus/privilege',
      'name' => 'Privilege Manager',
      'class_name' => NULL,
      'type' => '0',
      'belongs' => '6',
    ),
    5 => 
    array (
      'id' => '45',
      'route' => '/syntarsus/category',
      'name' => 'Category',
      'class_name' => NULL,
      'type' => '0',
      'belongs' => '6',
    ),
    6 => 
    array (
      'id' => '50',
      'route' => '/syntarsus/user/list',
      'name' => 'list',
      'class_name' => NULL,
      'type' => '1',
      'belongs' => '9',
    ),
    7 => 
    array (
      'id' => '51',
      'route' => '/syntarsus/user/listestructure',
      'name' => 'listestructure',
      'class_name' => NULL,
      'type' => '1',
      'belongs' => '9',
    ),
    8 => 
    array (
      'id' => '52',
      'route' => '/syntarsus/user/insert',
      'name' => 'insert',
      'class_name' => NULL,
      'type' => '1',
      'belongs' => '9',
    ),
    9 => 
    array (
      'id' => '53',
      'route' => '/syntarsus/user/changestate',
      'name' => 'changestate',
      'class_name' => NULL,
      'type' => '1',
      'belongs' => '9',
    ),
    10 => 
    array (
      'id' => '54',
      'route' => '/syntarsus/user/listrol',
      'name' => 'listrol',
      'class_name' => NULL,
      'type' => '1',
      'belongs' => '9',
    ),
    11 => 
    array (
      'id' => '55',
      'route' => '/syntarsus/user/asignrol',
      'name' => 'asignrol',
      'class_name' => NULL,
      'type' => '1',
      'belongs' => '9',
    ),
    12 => 
    array (
      'id' => '56',
      'route' => '/syntarsus/user/edit',
      'name' => 'edit',
      'class_name' => NULL,
      'type' => '1',
      'belongs' => '9',
    ),
    13 => 
    array (
      'id' => '57',
      'route' => '/syntarsus/user/delete',
      'name' => 'delete',
      'class_name' => NULL,
      'type' => '1',
      'belongs' => '9',
    ),
    14 => 
    array (
      'id' => '58',
      'route' => '/syntarsus/category/list',
      'name' => 'list',
      'class_name' => NULL,
      'type' => '1',
      'belongs' => '45',
    ),
    15 => 
    array (
      'id' => '59',
      'route' => '/syntarsus/category/insert',
      'name' => 'insert',
      'class_name' => NULL,
      'type' => '1',
      'belongs' => '45',
    ),
    16 => 
    array (
      'id' => '60',
      'route' => '/syntarsus/category/edit/:id',
      'name' => 'edit_:id',
      'class_name' => NULL,
      'type' => '1',
      'belongs' => '45',
    ),
    17 => 
    array (
      'id' => '61',
      'route' => '/syntarsus/category/delete/:id',
      'name' => 'delete_:id',
      'class_name' => NULL,
      'type' => '1',
      'belongs' => '45',
    ),
    18 => 
    array (
      'id' => '62',
      'route' => '/syntarsus/rol/list',
      'name' => 'list',
      'class_name' => NULL,
      'type' => '1',
      'belongs' => '27',
    ),
    19 => 
    array (
      'id' => '63',
      'route' => '/syntarsus/rol/insert',
      'name' => 'insert',
      'class_name' => NULL,
      'type' => '1',
      'belongs' => '27',
    ),
    20 => 
    array (
      'id' => '64',
      'route' => '/syntarsus/rol/edit',
      'name' => 'edit',
      'class_name' => NULL,
      'type' => '1',
      'belongs' => '27',
    ),
    21 => 
    array (
      'id' => '65',
      'route' => '/syntarsus/rol/delete',
      'name' => 'delete',
      'class_name' => NULL,
      'type' => '1',
      'belongs' => '27',
    ),
    22 => 
    array (
      'id' => '66',
      'route' => '/syntarsus/rol/asignprivilege',
      'name' => 'asignprivilege',
      'class_name' => NULL,
      'type' => '1',
      'belongs' => '27',
    ),
    23 => 
    array (
      'id' => '67',
      'route' => '/syntarsus/rol/listprivileges',
      'name' => 'listprivileges',
      'class_name' => NULL,
      'type' => '1',
      'belongs' => '27',
    ),
    24 => 
    array (
      'id' => '68',
      'route' => '/syntarsus/privilege/list',
      'name' => 'list',
      'class_name' => NULL,
      'type' => '1',
      'belongs' => '34',
    ),
    25 => 
    array (
      'id' => '69',
      'route' => '/syntarsus/privilege/listaction',
      'name' => 'listaction',
      'class_name' => NULL,
      'type' => '1',
      'belongs' => '34',
    ),
    26 => 
    array (
      'id' => '70',
      'route' => '/syntarsus/privilege/listroutes',
      'name' => 'listroutes',
      'class_name' => NULL,
      'type' => '1',
      'belongs' => '34',
    ),
    27 => 
    array (
      'id' => '71',
      'route' => '/syntarsus/privilege/addDir',
      'name' => 'addDir',
      'class_name' => NULL,
      'type' => '1',
      'belongs' => '34',
    ),
    28 => 
    array (
      'id' => '72',
      'route' => '/syntarsus/privilege/addIndex',
      'name' => 'addIndex',
      'class_name' => NULL,
      'type' => '1',
      'belongs' => '34',
    ),
    29 => 
    array (
      'id' => '73',
      'route' => '/syntarsus/privilege/insertaction',
      'name' => 'insertaction',
      'class_name' => NULL,
      'type' => '1',
      'belongs' => '34',
    ),
    30 => 
    array (
      'id' => '74',
      'route' => '/syntarsus/privilege/editaction',
      'name' => 'editaction',
      'class_name' => NULL,
      'type' => '1',
      'belongs' => '34',
    ),
    31 => 
    array (
      'id' => '75',
      'route' => '/syntarsus/privilege/deleteaction',
      'name' => 'deleteaction',
      'class_name' => NULL,
      'type' => '1',
      'belongs' => '34',
    ),
    32 => 
    array (
      'id' => '76',
      'route' => '/syntarsus/privilege/edit',
      'name' => 'edit',
      'class_name' => NULL,
      'type' => '1',
      'belongs' => '34',
    ),
    33 => 
    array (
      'id' => '77',
      'route' => '/syntarsus/privilege/delete',
      'name' => 'delete',
      'class_name' => NULL,
      'type' => '1',
      'belongs' => '34',
    ),
    34 => 
    array (
      'id' => '78',
      'route' => '/syntarsus/estructure',
      'name' => 'Estructure',
      'class_name' => NULL,
      'type' => '0',
      'belongs' => '6',
    ),
    35 => 
    array (
      'id' => '79',
      'route' => '/syntarsus/estructure/list',
      'name' => 'list',
      'class_name' => NULL,
      'type' => '1',
      'belongs' => '78',
    ),
    36 => 
    array (
      'id' => '80',
      'route' => '/syntarsus/estructure/listcategory',
      'name' => 'listcategory',
      'class_name' => NULL,
      'type' => '1',
      'belongs' => '78',
    ),
    37 => 
    array (
      'id' => '81',
      'route' => '/syntarsus/estructure/insert',
      'name' => 'insert',
      'class_name' => NULL,
      'type' => '1',
      'belongs' => '78',
    ),
    38 => 
    array (
      'id' => '82',
      'route' => '/syntarsus/estructure/edit',
      'name' => 'edit',
      'class_name' => NULL,
      'type' => '1',
      'belongs' => '78',
    ),
    39 => 
    array (
      'id' => '83',
      'route' => '/syntarsus/estructure/delete',
      'name' => 'delete',
      'class_name' => NULL,
      'type' => '1',
      'belongs' => '78',
    ),
    40 => 
    array (
      'id' => '84',
      'route' => '/syntarsus/auditories',
      'name' => 'Auditories',
      'class_name' => NULL,
      'type' => '0',
      'belongs' => '6',
    ),
    41 => 
    array (
      'id' => '85',
      'route' => '/syntarsus/auditories/list',
      'name' => 'list',
      'class_name' => NULL,
      'type' => '1',
      'belongs' => '84',
    ),
    42 => 
    array (
      'id' => '86',
      'route' => '/syntarsus/auditories/delete',
      'name' => 'delete',
      'class_name' => NULL,
      'type' => '1',
      'belongs' => '84',
    ),
    43 => 
    array (
      'id' => '87',
      'route' => '/syntarsus/auditories/listestadistic',
      'name' => 'listestadistic',
      'class_name' => NULL,
      'type' => '1',
      'belongs' => '84',
    ),
  ),
  'security_rol_security_privilege' => 
  array (
    0 => 
    array (
      'id_rol' => '4',
      'id_privilege' => '6',
    ),
    1 => 
    array (
      'id_rol' => '4',
      'id_privilege' => '9',
    ),
    2 => 
    array (
      'id_rol' => '4',
      'id_privilege' => '27',
    ),
    3 => 
    array (
      'id_rol' => '4',
      'id_privilege' => '34',
    ),
    4 => 
    array (
      'id_rol' => '4',
      'id_privilege' => '45',
    ),
    5 => 
    array (
      'id_rol' => '4',
      'id_privilege' => '50',
    ),
    6 => 
    array (
      'id_rol' => '4',
      'id_privilege' => '51',
    ),
    7 => 
    array (
      'id_rol' => '4',
      'id_privilege' => '52',
    ),
    8 => 
    array (
      'id_rol' => '4',
      'id_privilege' => '53',
    ),
    9 => 
    array (
      'id_rol' => '4',
      'id_privilege' => '54',
    ),
    10 => 
    array (
      'id_rol' => '4',
      'id_privilege' => '55',
    ),
    11 => 
    array (
      'id_rol' => '4',
      'id_privilege' => '56',
    ),
    12 => 
    array (
      'id_rol' => '4',
      'id_privilege' => '57',
    ),
    13 => 
    array (
      'id_rol' => '4',
      'id_privilege' => '58',
    ),
    14 => 
    array (
      'id_rol' => '4',
      'id_privilege' => '59',
    ),
    15 => 
    array (
      'id_rol' => '4',
      'id_privilege' => '60',
    ),
    16 => 
    array (
      'id_rol' => '4',
      'id_privilege' => '61',
    ),
    17 => 
    array (
      'id_rol' => '4',
      'id_privilege' => '62',
    ),
    18 => 
    array (
      'id_rol' => '4',
      'id_privilege' => '63',
    ),
    19 => 
    array (
      'id_rol' => '4',
      'id_privilege' => '64',
    ),
    20 => 
    array (
      'id_rol' => '4',
      'id_privilege' => '65',
    ),
    21 => 
    array (
      'id_rol' => '4',
      'id_privilege' => '66',
    ),
    22 => 
    array (
      'id_rol' => '4',
      'id_privilege' => '67',
    ),
    23 => 
    array (
      'id_rol' => '4',
      'id_privilege' => '68',
    ),
    24 => 
    array (
      'id_rol' => '4',
      'id_privilege' => '69',
    ),
    25 => 
    array (
      'id_rol' => '4',
      'id_privilege' => '70',
    ),
    26 => 
    array (
      'id_rol' => '4',
      'id_privilege' => '71',
    ),
    27 => 
    array (
      'id_rol' => '4',
      'id_privilege' => '72',
    ),
    28 => 
    array (
      'id_rol' => '4',
      'id_privilege' => '73',
    ),
    29 => 
    array (
      'id_rol' => '4',
      'id_privilege' => '74',
    ),
    30 => 
    array (
      'id_rol' => '4',
      'id_privilege' => '75',
    ),
    31 => 
    array (
      'id_rol' => '4',
      'id_privilege' => '76',
    ),
    32 => 
    array (
      'id_rol' => '4',
      'id_privilege' => '77',
    ),
    33 => 
    array (
      'id_rol' => '4',
      'id_privilege' => '78',
    ),
    34 => 
    array (
      'id_rol' => '4',
      'id_privilege' => '79',
    ),
    35 => 
    array (
      'id_rol' => '4',
      'id_privilege' => '80',
    ),
    36 => 
    array (
      'id_rol' => '4',
      'id_privilege' => '81',
    ),
    37 => 
    array (
      'id_rol' => '4',
      'id_privilege' => '82',
    ),
    38 => 
    array (
      'id_rol' => '4',
      'id_privilege' => '83',
    ),
    39 => 
    array (
      'id_rol' => '4',
      'id_privilege' => '84',
    ),
    40 => 
    array (
      'id_rol' => '4',
      'id_privilege' => '85',
    ),
    41 => 
    array (
      'id_rol' => '4',
      'id_privilege' => '86',
    ),
    42 => 
    array (
      'id_rol' => '4',
      'id_privilege' => '87',
    ),
  ),
  'security_rol' => 
  array (
    0 => 
    array (
      'id' => '4',
      'name' => 'Raptor admin',
    ),
  ),
  'security_trace' => 
  array (),
  'security_user' => 
  array (
    0 => 
    array (
      'id' => '12',
      'id_estructure' => '1',
      'id_rol' => '4',
      'fullname' => 'admin',
      'username' => 'admin',
      'email' => '',
      'password' => '$2y$10$Twug2IP4BoOOaMxHjXZoMeQNGVMuta9LXyWSQpf8yGkzrTGsI5EjG',
      'state' => '1',
      'icon' => NULL,
      'attempts' => '0',
      'lastattempt' => '2016-01-17 20:52:22',
    ),
  ),
);

