<?php
 /**
  * THIS FILE IS GENERATED BY RAPTOR EXPORTER, TO EASLY UPLOAD THIS FILE AGAIN INTO THE 
  * DATABASE USE THE IMPORTER CLASS.
  * 
  * Generated January 15 2016 10:23:55 PM
  */
 
$create=array (
  0 => '\\examples\\exampleBundle\\Model\\Entity\\Persona',
);
$data=array (
  'persona' => 
  array (
    0 => 
    array (
      'id' => '1',
      'nombre' => 'Liams',
      'apellidos' => 'Adam',
      'edad' => '25',
      'sexo' => '1',
    ),
    1 => 
    array (
      'id' => '2',
      'nombre' => 'Liams',
      'apellidos' => 'Adam',
      'edad' => '25',
      'sexo' => '1',
    ),
  ),
);

