<?php

namespace Raptor\Component\systemBundle\Model\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RaptorSessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaptorSessionRepository extends EntityRepository
{
    public function getGarvage($max) {
        $a=time()-$max;
        $query= $this->getEntityManager()->createQuery('SELECT e FROM Raptor\Component\systemBundle\Model\Entity\RaptorSession e WHERE e.time < ?1 ');
        $query->setParameter(1,$a);
       
        return $query->getResult();
    }
}